# video_generator/generator.py
import os
import random
import argparse # Import argparse
import pyttsx3 # Added for TTS
import time # Added for potential timing/unique naming
import tempfile # Added for temporary file creation
from PIL import Image, ImageDraw, ImageFont
from moviepy.editor import (VideoFileClip, # Used for loading video and audio
                            ImageClip,     # Used for images
                            AudioFileClip, # Used for loading audio, and getting duration
                            CompositeVideoClip, # Used for composing video
                            TextClip,      # Will be used for word-level animation
                            concatenate_videoclips)
from moviepy.video.fx.all import resize


ASSETS_DIR = os.path.join(os.path.dirname(__file__), 'assets')
BACKGROUNDS_DIR = os.path.join(ASSETS_DIR, 'backgrounds')
MUSIC_DIR = os.path.join(ASSETS_DIR, 'music')
QUOTES_FILE = os.path.join(ASSETS_DIR, 'quotes.txt')
DEFAULT_FONT_PATH = "arial.ttf"
VIDEO_WIDTH = 1920
VIDEO_HEIGHT = 1080
VIDEO_FPS = 24
# Directory for temporary audio files generated by TTS
TEMP_AUDIO_DIR = os.path.join(os.path.dirname(__file__), 'temp_audio')

# Global variables for pyttsx3 word event callback
# This is a common pattern for pyttsx3 callbacks when not using a class structure.
_word_event_capture_list = []
_timer_start_time = 0
_original_text_for_tts = ""

def _on_start_word_callback(name, location, length):
    """Callback executed by pyttsx3 when it starts speaking a word."""
    global _word_event_capture_list, _timer_start_time, _original_text_for_tts
    current_time_offset = time.time() - _timer_start_time
    word_text = _original_text_for_tts[location : location + length]
    _word_event_capture_list.append({
        'text': word_text,
        'start_time_offset': current_time_offset, # Raw time offset from when engine.say() was called
        'char_location': location,
        'char_length': length
    })
    # For debugging: print(f"Word: {word_text}, Offset: {current_time_offset:.3f}s, Loc: {location}, Len: {length}")


def get_random_file(directory, file_extensions=None):
    """Selects a random file from a directory.
    Optionally filters by a list of file extensions."""
    if not os.path.isdir(directory):
        print(f"Error: Directory '{directory}' not found.")
        return None

    files = os.listdir(directory)
    if file_extensions:
        files = [f for f in files if f.lower().endswith(tuple(ext.lower() for ext in file_extensions))] # ensure lowercase for comparison

    if not files:
        print(f"Error: No suitable files found in '{directory}'.")
        return None
    return os.path.join(directory, random.choice(files))

def get_background_clip(background_path=None, duration=10):
    """Loads a background image or video, resizes it, and sets its duration."""
    clip = None
    temp_bg_path_to_clean = None

    if background_path is None:
        background_path = get_random_file(BACKGROUNDS_DIR, ['.mp4', '.avi', '.mov', '.jpg', '.jpeg', '.png'])

    if not background_path or not os.path.exists(background_path):
        print(f"Warning: Background file '{background_path}' not found or not specified. Using fallback black background.")
        black_bg_pil = Image.new('RGB', (VIDEO_WIDTH, VIDEO_HEIGHT), color='black')
        # Use a unique temp name to avoid clashes if multiple fallbacks are somehow created
        temp_bg_path_to_clean = f"temp_black_bg_{random.randint(1000,9999)}.png"
        black_bg_pil.save(temp_bg_path_to_clean)
        clip = ImageClip(temp_bg_path_to_clean, duration=duration).set_fps(VIDEO_FPS)

    elif background_path.lower().endswith(('.jpg', '.jpeg', '.png')):
        clip = ImageClip(background_path, duration=duration)
    elif background_path.lower().endswith(('.mp4', '.avi', '.mov')):
        clip = VideoFileClip(background_path, audio=False)
        if clip.duration < duration:
            clip = clip.loop(duration=duration)
        clip = clip.subclip(0, duration)
    else:
        print(f"Error: Unsupported background file format: {background_path}. Using fallback black background.")
        black_bg_pil = Image.new('RGB', (VIDEO_WIDTH, VIDEO_HEIGHT), color='black')
        temp_bg_path_to_clean = f"temp_black_bg_{random.randint(1000,9999)}.png"
        black_bg_pil.save(temp_bg_path_to_clean)
        clip = ImageClip(temp_bg_path_to_clean, duration=duration).set_fps(VIDEO_FPS)

    if clip:
        clip = clip.resize(newsize=(VIDEO_WIDTH, VIDEO_HEIGHT))
        clip = clip.set_fps(VIDEO_FPS)

    # Store the path of the temporary file if one was created, so it can be cleaned up
    if temp_bg_path_to_clean and clip:
        clip.temp_bg_path = temp_bg_path_to_clean
    elif temp_bg_path_to_clean and not clip: # Should not happen if logic is correct
        try: os.remove(temp_bg_path_to_clean) # Clean up if clip creation failed
        except Exception: pass

    return clip


def get_quotes(quote_file_path=QUOTES_FILE): # Renamed parameter for clarity
    """Reads quotes from a file. Expects one quote per line."""
    if not os.path.exists(quote_file_path):
        print(f"Warning: Quotes file '{quote_file_path}' not found. Using default quote.")
        return ["This is a default quote. Create assets/quotes.txt to add your own."]
    try:
        with open(quote_file_path, 'r', encoding='utf-8') as f:
            quotes = [line.strip() for line in f if line.strip()]
        return quotes if quotes else ["No quotes found in file. Add some to the specified quotes file."]
    except Exception as e:
        print(f"Error reading quotes file '{quote_file_path}': {e}")
        return ["Error reading quotes. Please check the specified quotes file."]

def create_quote_image(text, image_size=(VIDEO_WIDTH, VIDEO_HEIGHT), font_path=DEFAULT_FONT_PATH, font_size=70, text_color=(255, 255, 255, 220), bg_color=(0,0,0,0)):
    """Creates a transparent image with the given text."""
    img = Image.new('RGBA', image_size, bg_color)
    draw = ImageDraw.Draw(img)
    font = None

    try:
        font = ImageFont.truetype(font_path, font_size)
    except IOError:
        print(f"Warning: Font '{font_path}' not found. Trying 'arial.ttf'.")
        try:
            font = ImageFont.truetype("arial.ttf", font_size) # Try arial as a common fallback
        except IOError:
            print(f"Warning: Font 'arial.ttf' also not found. Using PIL's default font.")
            try:
                font = ImageFont.load_default()
                if hasattr(font, "getsize"): # old PIL
                    font_size = 20 # default font is small, try to make it larger if possible
                else: # modern Pillow, load_default might be better
                    # try to get a larger version of default if possible, though it's tricky
                    pass
                print("Using PIL's load_default() font. Consider installing 'arial.ttf' or specifying a valid font path for better results.")
            except Exception as e_font:
                print(f"Critical font error, even PIL default failed: {e_font}. Text rendering will likely fail.")
                # Draw a placeholder error message if possible
                try:
                    err_font = ImageFont.load_default() # Minimal possible font
                    draw.text((10,10), "Font Error", font=err_font, fill=(255,0,0,255))
                except: pass
                return img # Return image with error or blank

    if font is None: # Should be caught by above, but as a safeguard
        print("Critical: Font object is None. Cannot render text.")
        return img


    max_chars_per_line = 40
    lines = []
    if text and text.strip():
        words = text.split()
        current_line = ""
        for word in words:
            if len(current_line + " " + word) <= max_chars_per_line:
                current_line += (" " + word if current_line else word)
            else:
                lines.append(current_line)
                current_line = word
        lines.append(current_line)
    else:
        lines = ["No text provided."]

    wrapped_text = "\n".join(lines)

    text_x, text_y = 10, 10
    spacing = 4 # Line spacing

    if hasattr(draw, 'textbbox') and hasattr(font, 'getbbox'): # Modern Pillow
        # anchor 'lt' (left-top) for bbox calculation, then adjust
        bbox = draw.textbbox((0,0), wrapped_text, font=font, spacing=spacing, align="center")
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
        text_x = (image_size[0] - text_width) / 2
        text_y = (image_size[1] - text_height) / 2
    elif hasattr(draw, 'textsize'): # Older Pillow/PIL
        text_width, text_height = draw.textsize(wrapped_text, font=font, spacing=spacing)
        text_x = (image_size[0] - text_width) / 2
        text_y = (image_size[1] - text_height) / 2

    draw.text((text_x, text_y), wrapped_text, font=font, fill=text_color, spacing=spacing, align="center")

    return img


def get_music_clip(music_path=None):
    """Loads a music file as an AudioFileClip."""
    if music_path is None:
        music_path = get_random_file(MUSIC_DIR, ['.mp3', '.wav', '.ogg'])

    if not music_path or not os.path.exists(music_path):
        print(f"Warning: Music file '{music_path}' not found or not specified. No audio will be added.")
        return None
    try:
        return AudioFileClip(music_path)
    except Exception as e:
        print(f"Error loading audio file '{music_path}': {e}")
        return None

def generate_video(quote_text, output_filename="output.mp4", duration_per_quote=10,
                   background_path=None, music_path=None, font_path=DEFAULT_FONT_PATH,
                   font_size=70, use_tts=False):
    """Generates a single video clip with one quote.
       If use_tts is True, attempts to generate speech and synchronize words.
    """
    print(f"Generating video for quote: '{quote_text[:50]}...'")

    actual_duration = duration_per_quote
    final_audio_clip_resource = None
    speech_audio_path_temp = None
    word_events = [] # Initialize word_events
    temp_bg_to_remove_on_exit = None


    video_clips_for_composition = [] # List to hold background and text clips

    if use_tts:
        print("TTS enabled, attempting to generate speech audio and word events...")
        # Now expecting three return values: path, duration, events
        speech_audio_path_temp, speech_duration, word_events = generate_speech_audio(quote_text)

        if speech_audio_path_temp and speech_duration > 0:
            print(f"Speech audio generated: path={speech_audio_path_temp}, duration={speech_duration:.2f}s")
            actual_duration = speech_duration
            try:
                final_audio_clip_resource = AudioFileClip(speech_audio_path_temp)
            except Exception as e:
                print(f"Error loading speech audio into MoviePy clip: {e}. Fallback.")
                if final_audio_clip_resource and hasattr(final_audio_clip_resource, 'close'): final_audio_clip_resource.close()
                final_audio_clip_resource = None
                word_events = [] # Clear word events if audio loading failed
                # speech_audio_path_temp will be cleaned in finally, so don't reset to None here
        else:
            print("TTS generation failed or produced zero duration audio. Fallback.")
            word_events = [] # Clear word events if TTS failed
            # speech_audio_path_temp might still exist (e.g. empty file), will be cleaned in finally

    if not final_audio_clip_resource: # If TTS not used, or TTS audio part failed
        print("Using lofi music (if available) and specified/default duration for audio.")
        music_clip_res = get_music_clip(music_path)
        if music_clip_res:
            final_audio_clip_resource = music_clip_res
        else:
            print("No lofi music. Video might have no audio if TTS also failed/disabled.")

    # Initialize resources for finally block
    bg_clip_resource = None
    text_clips_resources = [] # For word TextClips or the single ImageClip
    video_clip_to_write = None

    try:
        bg_clip = get_background_clip(background_path, duration=actual_duration)
        if bg_clip is None: # Critical failure in background loading
            print("Error: Could not load or create a background clip. Aborting video generation.")
            # Cleanup speech audio if it was created and not used
            if speech_audio_path_temp and os.path.exists(speech_audio_path_temp):
                 try:
                     if final_audio_clip_resource and final_audio_clip_resource.filename == speech_audio_path_temp:
                         if hasattr(final_audio_clip_resource, 'close'): final_audio_clip_resource.close()
                         final_audio_clip_resource = None
                     os.remove(speech_audio_path_temp)
                 except Exception as e_del_early: print(f"Early cleanup error for {speech_audio_path_temp}: {e_del_early}")
            return

        bg_clip_resource = bg_clip
        if hasattr(bg_clip, 'temp_bg_path'): # Store path of temp bg for cleanup
            temp_bg_to_remove_on_exit = bg_clip.temp_bg_path
        video_clips_for_composition.append(bg_clip_resource)


        if bg_clip.duration == 0 and actual_duration > 0:
            print("Warning: Background clip has zero duration. Setting to actual_duration.")
            bg_clip = bg_clip.set_duration(actual_duration) # Ensure bg_clip_resource reflects this

        # Text handling: either synchronized words or a single static quote image
        if use_tts and word_events: # Check word_events specifically for sync
            print(f"Preparing synchronized word TextClips. Number of words: {len(word_events)}")
            for i, event in enumerate(word_events):
                if event['duration'] <= 0.01: # Skip words with very short or no duration
                    print(f"Skipping word '{event['text']}' due to zero/negative duration: {event['duration']:.3f}s")
                    continue

                word_font_size = font_size + 10
                try:
                    # method='caption' wraps text. For single words, 'label' might be simpler if no wrapping is desired.
                    # Using a fixed width for caption can help center blocks of text if a word is very long.
                    txt_clip = TextClip(event['text'], fontsize=word_font_size, font=font_path, color='white', bg_color='transparent', method='caption', size=(VIDEO_WIDTH*0.8, None), align='West')
                    txt_clip = txt_clip.set_start(event['start']).set_duration(event['duration']).set_position('center')

                    # Add fade effects for smoother appearance/disappearance
                    fade_effect_duration = 0.1 # seconds for fade-in and fade-out
                    # Ensure fade duration is not too long for short words (max half of word's duration for each fade)
                    actual_fade_duration = min(fade_effect_duration, event['duration'] / 2.0)

                    if actual_fade_duration > 0.01: # Only apply if fade duration is meaningful
                        txt_clip = txt_clip.fadein(actual_fade_duration).fadeout(actual_fade_duration)

                    video_clips_for_composition.append(txt_clip)
                    text_clips_resources.append(txt_clip)
                except Exception as e_txtclip:
                    print(f"Error creating TextClip for word '{event['text']}': {e_txtclip}")
        else:
            if use_tts and not word_events and speech_audio_path_temp: # TTS audio ok, but no word events
                 print("TTS audio generated, but word events missing/empty. Showing full quote text for TTS audio duration.")
            elif use_tts and not speech_audio_path_temp: # TTS failed completely
                 print("TTS failed. Showing full quote text for original duration_per_quote with lofi music (if any).")
            # else: TTS not used, normal operation handled by actual_duration and final_audio_clip_resource already.

            quote_img = create_quote_image(quote_text, font_path=font_path, font_size=font_size)
            full_quote_image_clip = ImageClip(quote_img).set_duration(actual_duration).set_position('center')
            video_clips_for_composition.append(full_quote_image_clip)
            text_clips_resources.append(full_quote_image_clip)


        video_clip_to_write = CompositeVideoClip(video_clips_for_composition, size=(VIDEO_WIDTH, VIDEO_HEIGHT))

        if final_audio_clip_resource:
            current_audio_duration = final_audio_clip_resource.duration
            if current_audio_duration < actual_duration:
                if hasattr(final_audio_clip_resource, 'loop') and actual_duration > 0:
                    final_audio_clip_resource = final_audio_clip_resource.loop(duration=actual_duration)
                elif actual_duration == 0 : # Ensure audio is silent if video duration is zero
                     final_audio_clip_resource = final_audio_clip_resource.subclip(0,0)

            video_clip_to_write = video_clip_to_write.set_audio(final_audio_clip_resource.subclip(0, actual_duration))

        video_clip_to_write = video_clip_to_write.set_fps(VIDEO_FPS)

        print(f"Writing video to {output_filename} (Duration: {actual_duration:.2f}s)...")
        video_clip_to_write.write_videofile(output_filename, codec="libx264", audio_codec="aac", temp_audiofile=f'temp-audio-{random.randint(1000,9999)}.m4a', remove_temp=True, logger='bar')
        print("Video generated successfully!")

    except Exception as e:
        print(f"Error during video generation or writing: {e}")
        import traceback
        traceback.print_exc()
    finally:
        # Clean up resources
        if bg_clip_resource and hasattr(bg_clip_resource, 'close'): bg_clip_resource.close()
        for txt_clip_res in text_clips_resources:
            if txt_clip_res and hasattr(txt_clip_res, 'close'): txt_clip_res.close()

        if video_clip_to_write and hasattr(video_clip_to_write, 'close'): video_clip_to_write.close()

        if final_audio_clip_resource and hasattr(final_audio_clip_resource, 'close'): final_audio_clip_resource.close()

        if speech_audio_path_temp and os.path.exists(speech_audio_path_temp):
            print(f"Cleaning up temporary speech audio file: {speech_audio_path_temp}")
            try:
                time.sleep(0.1)
                os.remove(speech_audio_path_temp)
            except Exception as e_del:
                print(f"Error deleting temporary speech audio file '{speech_audio_path_temp}': {e_del}")

        # Clean up temporary background file from get_background_clip (if created and path stored)
        if temp_bg_to_remove_on_exit and os.path.exists(temp_bg_to_remove_on_exit):
            try: os.remove(temp_bg_to_remove_on_exit)
            except Exception as e_remove: print(f"Error removing temporary background file {temp_bg_to_remove_on_exit}: {e_remove}")


def main():
    # Setup for basic test run if assets are missing
    if not os.path.exists(ASSETS_DIR):
        try: os.makedirs(ASSETS_DIR)
        except Exception as e: print(f"Could not create ASSETS_DIR: {e}")
    if not os.path.exists(BACKGROUNDS_DIR):
        try: os.makedirs(BACKGROUNDS_DIR)
        except Exception as e: print(f"Could not create BACKGROUNDS_DIR: {e}")
    if not os.path.exists(MUSIC_DIR):
        try: os.makedirs(MUSIC_DIR)
        except Exception as e: print(f"Could not create MUSIC_DIR: {e}")

    # Check if BACKGROUNDS_DIR is empty or only contains non-media files (e.g. .DS_Store)
    bg_dir_files = []
    try: bg_dir_files = os.listdir(BACKGROUNDS_DIR)
    except Exception as e: print(f"Could not list BACKGROUNDS_DIR: {e}")

    if not any(f.lower().endswith(('.png', '.jpg', '.jpeg', '.mp4', '.avi', '.mov')) for f in bg_dir_files):
        try:
            print("Creating dummy background as no valid media found in assets/backgrounds...")
            dummy_bg = Image.new('RGB', (VIDEO_WIDTH, VIDEO_HEIGHT), color='blue')
            dummy_bg.save(os.path.join(BACKGROUNDS_DIR, 'default_background.png'))
        except Exception as e:
            print(f"Could not create dummy background: {e}")

    if not os.path.exists(QUOTES_FILE) or (os.path.exists(QUOTES_FILE) and os.path.getsize(QUOTES_FILE) == 0):
        try:
            print("Creating dummy quotes file...")
            with open(QUOTES_FILE, 'w', encoding='utf-8') as f:
                f.write("This is a test quote from generator.py.\n")
                f.write("Another quote for testing purposes.\n")
        except Exception as e:
            print(f"Could not create dummy quotes file: {e}")

    parser = argparse.ArgumentParser(description="Generate a YouTube video with a quote, background, and lofi music.")
    parser.add_argument('--quote', type=str, help="A single quote string to display.")
    parser.add_argument('--quote_file', type=str, default=QUOTES_FILE, help=f"Path to a text file containing quotes (one per line). Defaults to {QUOTES_FILE}")
    parser.add_argument('--music_path', type=str, help="Path to a specific music file for background. If --use_tts is enabled, TTS audio will replace this background music.")
    parser.add_argument('--background_path', type=str, help="Path to a specific background image or video. If not provided, a random one from assets/backgrounds will be chosen.")
    parser.add_argument('--output_filename', type=str, default="output.mp4", help="Filename for the output video. Default: output.mp4")
    parser.add_argument('--duration', type=int, default=10, help="Duration of the video in seconds IF NOT using TTS. If using TTS, duration is determined by speech length. Default: 10s")
    parser.add_argument('--font_path', type=str, default=DEFAULT_FONT_PATH, help=f"Path to the .ttf font file. Default: {DEFAULT_FONT_PATH} (Ensure this font is available or in system path)")
    parser.add_argument('--font_size', type=int, default=70, help="Base font size for the quote. Default: 70. Individual words in TTS mode might be slightly larger.")

    # New TTS argument
    parser.add_argument('--use_tts', action='store_true', help="Enable Text-to-Speech for the quote. This will replace background music with the spoken quote and synchronize words if possible.")

    args = parser.parse_args()

    quote_to_use = None
    if args.quote:
        quote_to_use = args.quote
    else:
        # Use args.quote_file which defaults to QUOTES_FILE if not provided by user
        quotes_from_file = get_quotes(args.quote_file)
        if quotes_from_file and quotes_from_file[0] != "This is a default quote. Create assets/quotes.txt to add your own." and not quotes_from_file[0].startswith("Error reading quotes"): # check if actual quotes were loaded
            quote_to_use = random.choice(quotes_from_file)
        elif quotes_from_file and quotes_from_file[0] == "This is a default quote. Create assets/quotes.txt to add your own.":
             quote_to_use = quotes_from_file[0] # Use the default placeholder
        else: # No quotes from file, and no --quote arg
            print("No quotes available from file or arguments. Using a final fallback quote.")
            quote_to_use = "This is a fallback quote. Please provide quotes via --quote or --quote_file."

    if not quote_to_use: # Should not be reached if logic above is correct
        print("Critical Error: No quote selected. Cannot generate video.")
        return

    generate_video(
        quote_text=quote_to_use,
        output_filename=args.output_filename,
        duration_per_quote=args.duration,
        background_path=args.background_path,
        music_path=args.music_path,
        font_path=args.font_path,
        font_size=args.font_size
    )

if __name__ == '__main__':
    main()
